Add HTTP proxy configuration
rabbitmq/rabbitmq-autocluster pull request #43
Opened 2017-08-22 08:25 UTC by noxdafox

In case of limited connectivity, this change allows to set HTTP(S) proxy to connect to the service discovery backend.

Credits to @jjonek.

2017-08-22 12:53 UTC, michaelklishin requested changes
Thank you. This looks like a good start but needs some naming changes IMO.

2017-08-22 12:53 UTC, michaelklishin commented on include/autocluster.hrl
> +         {config, no_proxy,              "NO_PROXY",              "undefined",   string,  false},
I find this name confusing. Please rename it to `proxy_exclude_list` or similar (`proxy_bypass_list`?)

2017-08-22 12:56 UTC, noxdafox commented on include/autocluster.hrl
> +         {config, no_proxy,              "NO_PROXY",              "undefined",   string,  false},
The no_proxy was taken from Erlang `httpc` APIs. I will change it in `proxy_exclusion_list`.

2017-08-22 12:58 UTC, noxdafox commented on include/autocluster.hrl
> +         {config, no_proxy,              "NO_PROXY",              "undefined",   string,  false},
Or even better: it will be a list and will be named only `proxy_exclusions`. I think is more clear like that.

2017-08-22 13:02 UTC, michaelklishin commented
Aslo, if you'd like to see a `3.6.x`-compatible release with these changes, please rebase against the `stable` branch.

2017-08-22 15:08 UTC, michaelklishin commented on include/autocluster.hrl
> +         {config, no_proxy,              "NO_PROXY",              "undefined",   string,  false},
@noxdafox sounds good.

2017-08-23 20:09 UTC, noxdafox commented
Rejecting as invalid, see PR #46.

2017-08-23 20:09 UTC, closed without merging